<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="laser_joint" type="fixed">
        <parent link="upper_link"/>
        <child link="laser_frame"/>
        <origin xyz="-${base_length /2.5} 0.005 0.06" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <cylinder radius="0.034" length="0.03"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.034" length="0.03"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*0.05}" h="${2*0.04}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link>
    <!--joint name="laser_joint_down" type="fixed">
        <parent link="upper_link"/>
        <child link="laser_frame_down"/>
        <origin xyz="-0.152  -0.012 0" rpy="0 0 0"/>
    </joint>
    <link name="laser_frame">
    </link>
    <joint name="laser_joint" type="fixed">
        <parent link="laser_frame_down"/>
        <child link="laser_frame"/>
        <origin xyz="0 0 -0.01" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame_down">
        <visual>
            <origin xyz="0.003 0.12 -0.043" rpy="1.57 0 0"/>
            <geometry>
                <mesh filename="package://robitcubebot_description/meshes/lidar.STL" scale="0.001 0.001 0.001" />
            </geometry>
            
            <material name="black">
                <color rgba="0.1 0.1 0.1 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://robitcubebot_description/meshes/lidar.STL" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="1.0" r="${2*0.05}" h="${2*0.04}" 
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
    </link-->
    <!--gazebo reference="laser_frame">
        <material>Gazebo/Red</material>

        <sensor name="laser" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo-->

</robot>